version: '3'

services:
  # Node.js service for React
  react:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-app
    ports:
      - "3000:80"
    networks:
      - react-network

  # Nginx service
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - react-network
    depends_on:
      - react

networks:
  react-network:
